wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entries"),
    path("search", views.search, name="search"),
    path("error", views.search, name="error"),
    path("create", views.create, name="create"),
    path("error_create", views.error_create, name="error_create"),
    path("wiki/edit/<str:title>", views.edit, name="edit"),
    path("random", views.random_page, name="random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from markdown2 import markdown
from django.urls import reverse

from . import util
import random

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    if util.get_entry(title):
        return render(request, "encyclopedia/entries.html", {
            "entry": markdown(util.get_entry(title)), "title": title
            })
    else:
        return render(request, "encyclopedia/error.html")

def search(request):
    user_input = request.GET.get("q")
    # If the user request matches exactly the entry
    if util.get_entry(user_input):
        return render(request, "encyclopedia/entries.html", {
            "entry": markdown(util.get_entry(user_input)), "title": user_input
            })

    # If user entry includes substring of the entry
    substring = []
    for e in util.list_entries():
        if user_input.lower() in e.lower():
            substring.append(e)
    if substring:
        return render(request, "encyclopedia/search.html", {
            "user_input": user_input, 
            "entries": substring
        })
    # No matches
    else:
        return render(request, "encyclopedia/error.html")

def create(request):
    if request.method == "GET":
        return render(request, "encyclopedia/create.html")
    if request.method == "POST":
        title = request.POST.get("title")
        if title in util.list_entries():
            return HttpResponseRedirect(reverse("encyclopedia:error_create"))
        definition = markdown(request.POST.get("definition"))
        util.save_entry(title, definition, True)
        return render(request, "encyclopedia/entries.html", {
                "entry": markdown(util.get_entry(title)), "title": title
                })

def error_create(request):
    return render(request, "encyclopedia/error_create.html")

def edit(request, title):
    description = util.get_entry(title)
    if request.method == "GET":
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "entry": description
        })
    if request.method == "POST":
        definition = request.POST.get("definition")
        util.save_entry(title, definition)
        return render(request, "encyclopedia/entries.html", {
                "entry": markdown(util.get_entry(title)), "title": title
                })     

def random_page(request):
    title = random.choice(util.list_entries())
    return render(request, "encyclopedia/entries.html", {
        "entry": markdown(util.get_entry(title)),
        "title": title
        })  

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create
{% endblock %}

{% block body %}
<form method="post" class="create">
    {% csrf_token %}
    <p> Write the title of your entry: </p>
    <input autocomplete="off" id="title" name="title" placeholder="title" type="text" required>
    <p> Write the deifinition of your entry: </p>
    <textarea name="definition" placeholder="definition" type="text"></textarea>
    <br>
    <button class="btn button primary-button mr-4 text-uppercase" type="submit">Submit</button>
</form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}

<form method="post" class="edit">
    {% csrf_token %}
    <p> Edit the entry: </p>
    <textarea name="definition" placeholder="definition" type="text" value="entry" required>{{ entry }}
    </textarea>
    <br>
    <button class="btn button primary-button mr-4 text-uppercase" type="submit">Save</button>
</form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entries.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    {{ title }}

{% endblock %}

{% block body %}

    <p>{{ entry | safe }}
        <a href="{% url 'encyclopedia:edit' title %}"> edit </a>
    </p>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    Error
    
{% endblock %}

{% block body %}

    <h4>Page not found.</h4>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error_create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    Error
    
{% endblock %}

{% block body %}

    <h4>This entry already exists.</h4>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
        <li> 
            <a href="{% url 'encyclopedia:entries' entry %}">
                {{ entry }} 
            </a> 
        </li>
        {% endfor %}
    </ul>
{% endblock %}

        
                    

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>         
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/random.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <p>
        {{ entry }}
    </p>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>Results for: {{ user_input }}</h1>
    <ul>
        {% for entry in entries %}
        <li> 
            <a href="{% url 'encyclopedia:entries' entry %}">
                {{ entry }} 
            </a> 
        </li>
        {% endfor %}    
    </ul>
{% endblock %}